version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app/backend 
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
    depends_on:
      - backend
